spring:
  profiles:
    active: ${SPRING_PROFILE:postgres}

---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:file:./data/assurance_db;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/assurance_sante_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
    username: ${DB_USER:assurance_app}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

---
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    url: ${DB_URL:jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:assurance_db}}
    username: ${DB_USER:${PGUSER:admin}}
    password: ${DB_PASSWORD:${PGPASSWORD:admin123}}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

---

# Configuration commune à tous les profils
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: ${PORT:3001}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
  health:
    mail:
      enabled: false

app:
  jwtSecret: ${JWT_SECRET:k3untQX7VPALDigJxFzzKchYmxbdnJhIyCfVKzMxDB2FauysInXc100PUl9zSfmDYcYeg5QOoB9Btm2iNY4P4A==}
  jwtExpirationMs: ${JWT_EXPIRATION_MS:86400000}
